# -*- coding: utf-8 -*-
"""2602070300_ModelDeployment-No3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NxtopuYiuIntmxKiYCRu4ZbgeHyGjN8D
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from xgboost import XGBClassifier
import pickle
from sklearn.impute import SimpleImputer
import matplotlib.pyplot as plt

# Fungsi untuk prediksi
def predict_churn(input_data):
    # Memuat model terbaik yang telah disimpan
    with open("XGBoost.pkl", "rb") as file:
        loaded_model = pickle.load(file)

    # Menggunakan model untuk prediksi
    input_features = input_data[["CreditScore", "Age", "Tenure", "Balance", "NumOfProducts", "HasCrCard", "IsActiveMember", "EstimatedSalary"]]
    input_features_scaled = StandardScaler().fit_transform(input_features)
    prediction = loaded_model.predict(input_features_scaled)

    return prediction

input_data = pd.DataFrame({
    "CreditScore": [750],
    "Age": [35],
    "Tenure": [5],
    "Balance": [10000],
    "NumOfProducts": [3],
    "HasCrCard": [1],
    "IsActiveMember": [1],
    "EstimatedSalary": [50000]
})

prediction = predict_churn(input_data)
print("O = customer attrition or subscription cancellation")
print("1 = customer will churn")

print("Prediction:", prediction)